# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Define the number of compute nodes
    num_nodes = 2  # Adjust this number as needed
  
    # Base VM settings
    config.vm.box = "ubuntu/jammy64"
    controller_name = "sl1"
    # Configure the SLURM controller node
    config.vm.define controller_name do |controller|
      controller.vm.hostname = controller_name
      controller.vm.network "private_network", ip: "192.168.56.10"
  
      controller.vm.provider "virtualbox" do |vb|
        vb.name = controller_name # This sets the name displayed in VirtualBox
        vb.memory = "10240"
        vb.cpus = 10
      end
      config.vm.provision "file", source: "slurm.conf", destination: "/tmp/slurm.conf"

      controller.vm.provision "shell", inline: <<-SHELL

        # Create slurm user
        # Update and install dependencies
        apt-get update
        apt-get install -y build-essential munge libmunge-dev slurm-wlm slurm-wlm-basic-plugins slurmctld

        # Configure Munge for authentication
        dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key
        chown -R munge: /etc/munge
        chmod 0700 /etc/munge
        systemctl enable munge
        systemctl start munge


        # Setup directories and permissions
        mkdir -p /var/spool/slurmctld /var/spool/slurmd /var/log/slurm /etc/slurm-llnl/
        chown -R slurm: /var/spool/slurmctld /var/spool/slurmd /var/log/slurm /etc/slurm-llnl/
        chmod 755 /var/spool/slurmctld /var/spool/slurmd /var/log/slurm /etc/slurm-llnl/

        sudo cp /vagrant/slurm.conf /etc/slurm-llnl/slurm.conf
        sudo chown slurm:slurm /etc/slurm-llnl/slurm.conf
        sudo cp /vagrant/slurm.conf /etc/slurm/slurm.conf
        sudo chown slurm:slurm /etc/slurm/slurm.conf

    
  
        # Ensure slurm.conf is owned by slurm user
        chown slurm: /etc/slurm/slurm.conf
        chmod 644 /etc/slurm/slurm.conf
  
        # Start SLURM controller daemon
        systemctl enable slurmctld
        systemctl start slurmctld

        echo "Overwriting /etc/hosts with custom hosts file"
        sudo cp /vagrant/hosts /etc/hosts

      SHELL

    end
  
end
  



